name: Extension packaging and create draft release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout current extension
        uses: actions/checkout@v6
        with:
          path: ${{ github.repository }}
      - name: Create package
        uses: thedoctor0/zip-release@0.7.6
        with:
          filename: ../${{ github.repository }}-${{ github.ref_name }}.zip
          path: '*'
          directory: ${{ github.repository_owner }}
          exclusions: >-
            *.git*
            ${{ github.event.repository.name }}/README.md
            ${{ github.event.repository.name }}/rename_extension.sh
            ${{ github.event.repository.name }}/docs/*
            ${{ github.event.repository.name }}/docs/
            ${{ github.event.repository.name }}/tests/*
            ${{ github.event.repository.name }}/tests/
      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ github.repository }}-${{ github.ref_name }}.zip
          artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          updateOnlyUnreleased: true
          body: |
            ## Documentation

            <!--TODO: Check the following URL and replace TBD maybe with ${{ github.ref_name }} -->
            **DokuWiki**: https://wiki.itomig.de/itomig-code:${{ github.repository }}:TBD

            ## Release Notes
